# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

paginate_path: "page:num"

# Setup
title:            Anmol Kapoor
tagline:          'My web space'
description:      '~Working on tag line~'
url:              http://anmolkapoor.in
baseurl:          /

author:
  name:           'Anmol Kapoor'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

defaults:
- scope:
    path: "" # an empty string here means all files in the project
  values:
    read_minutes: 9
    author: "Anmol Kapoor"
    single_side_bar_image: /public/images/header_0.jpg
    side_bar_image: /public/images/header_0.jpg
    use_different_side_bar_image: true
    comments: false
    resume_link: /public/files/Anmol_kapoor_resume_website.pdf
